export const FORGEOS_HUB_PORT = 25463; // FORGEOS
export const FORGEOS_HUB_DEV_PORT = 25466; // USED IN DEV ENV ONLY, to avoid conflicts with production FORGEOS HUB
export const FORGEOS_DEFAULT_RPC_PORT = 4317;
export const RPC_ADDRESS_BASE = "127.0.0.1";
export const FORGEOS_DEFAULT_RPC_ADDRESS = `${RPC_ADDRESS_BASE}:${FORGEOS_DEFAULT_RPC_PORT}`;
